cursor #ecdfe5
cursor_text_color #d2c2ca

foreground            #ecdfe5
background            #181215
selection_foreground  #3e2a38
selection_background  #dcbed0
url_color             #f6b2e0

color0   #181215
color1   #ff727e
color2   #9ef67b
color3   #ffe072
color4   #e99cd0
color5   #71385f
color6   #f6b2e0
color7   #ffeffa
color8   #494046
color9   #ff9fa7
color10  #bfffa5
color11  #ffeba5
color12  #ffc3eb
color13  #ffcdef
color14  #ffdff4
color15  #fff8fc
