effects = curves:vibrance:cas
reshadeTexturePath = "/opt/reshade/textures"
reshadeIncludePath = "/opt/reshade/shaders"

vibrance = /opt/reshade/shaders/SweetFX/Vibrance.fx
curves = /opt/reshade/shaders/SweetFX/Curves.fx
denoise = /opt/reshade/shaders/Denoise.fx

casSharpness = 0.7
Vibrance = -0.15
Curves = 0.35
