effects = vibrance:curves:cas
reshadeTexturePath = "/opt/reshade/textures"
reshadeIncludePath = "/opt/reshade/shaders"

vibrance = /opt/reshade/shaders/SweetFX/Vibrance.fx
curves = /opt/reshade/shaders/SweetFX/Curves.fx

casSharpness = 0.9
Vibrance = 0.15
Curves = 0.15
