effects = vibrance:curves:cas
reshadeTexturePath = "/opt/reshade/textures"
reshadeIncludePath = "/opt/reshade/shaders"

vibrance = /opt/reshade/shaders/SweetFX/Vibrance.fx
curves = /opt/reshade/shaders/SweetFX/Curves.fx
denoise = /opt/reshade/shaders/Denoise.fx

casSharpness = 1.0
Vibrance = 0.65
Curves = 0.65
