return {
  'rmagatti/goto-preview',
  keys = {
    { "gpd", desc = "Preview definition" },
    { "gpt", desc = "Preview type definition" },
    { "gpi", desc = "Preview implementation" },
    { "gpr", desc = "Preview references" },
    { "gP", desc = "Close all previews" },
  },
  opts = {
    width = 121,
    height = 16,
    border = {"↖", "─" ,"┐", "│", "┘", "─", "└", "│"},
    default_mappings = true,
    debug = false,
    opacity = nil,
    resizing_mappings = false,
    focus_on_open = true,
    dismiss_on_move = false,
    force_close = true,
    bufhidden = "wipe",
    stack_floating_preview_windows = true,
    preview_window_title = { enable = true, position = "left" },
  },
}
