return {
    -- {
    --     'nvim-telescope/telescope.nvim',
    --     branch = '0.1.x',
    --     cmd = "Telescope",
    --     keys = {
    --         { '<leader>ff', '<cmd>Telescope find_files<cr>', desc = 'Telescope: Find files' },
    --         { '<leader>fw', '<cmd>Telescope grep_string<cr>', desc = 'Telescope: Find current word' },
    --         { '<leader>fg', '<cmd>Telescope live_grep<cr>', desc = 'Telescope: Find by grep' },
    --         { '<leader>fd', '<cmd>Telescope diagnostics<cr>', desc = 'Telescope: Find diagnostics' },
    --         { '<leader>fb', '<cmd>Telescope buffers<cr>', desc = 'Telescope: Find buffers' },
    --         { '<leader>fS', '<cmd>Telescope git_status<cr>', desc = 'Telescope: Find git status' },
    --         { '<leader>fh', '<cmd>Telescope harpoon marks<cr>', desc = 'Telescope: Harpoon Marks' },
    --         { '<leader>fr', '<cmd>Telescope git_worktree git_worktrees<cr>', desc = 'Telescope: Git Worktrees' },
    --         { '<leader>fR', '<cmd>Telescope git_worktree create_git_worktree<cr>', desc = 'Telescope: Create Git Worktree' },
    --         { '<leader>fn', '<cmd>Telescope notify notify<cr>', desc = 'Telescope: Notify' },
    --         { 'st', '<cmd>TodoTelescope<cr>', desc = 'Telescope: Todo' },
    --         { '<leader><tab>', '<cmd>Telescope commands<cr>', desc = 'Telescope: Commands' },
    --         { '<leader>?', '<cmd>Telescope keymaps<cr>', desc = 'Telescope: Keymaps' },
    --         { '<leader>/', '<cmd>Telescope current_buffer_fuzzy_find<cr>', desc = 'Telescope: Fuzzy search current buffer' },
    --     },
    --     dependencies = {
    --         'nvim-lua/plenary.nvim',
    --         'nvim-telescope/telescope-fzf-native.nvim',
    --         'nvim-telescope/telescope-symbols.nvim',
    --     },
    --     opts = {
    --         defaults = {
    --             layout_strategy = "horizontal",
    --             layout_config = {
    --                 preview_width = 0.65,
    --                 horizontal = { size = { width = "95%", height = "95%" } },
    --             },
    --             pickers = { find_files = { theme = "dropdown" } },
    --             mappings = {
    --                 i = {
    --                     ['<C-u>'] = false,
    --                     ['<C-d>'] = false,
    --                     ["<C-j>"] = require('telescope.actions').move_selection_next,
    --                     ["<C-k>"] = require('telescope.actions').move_selection_previous,
    --                 },
    --             },
    --         },
    --     },
    --     config = function()
    --         pcall(require('telescope').load_extension, 'fzf')
    --     end,
    -- },
    -- {
    --     'nvim-telescope/telescope-fzf-native.nvim',
    --     build = 'make',
    --     cond = vim.fn.executable 'make' == 1,
    -- },
    -- 'nvim-telescope/telescope-symbols.nvim',
}
