[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0
normal = { family = "monospace", style = "Regular" }

[window]
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "Buttonless"
opacity = 0.6
dynamic_title = false


[scrolling]
history = 99999
