[colors.primary]
background = '#181215'
foreground = '#ecdfe5'

[colors.selection]
text = '#ecdfe5'
background = '#68355b'

[colors.cursor]
text = '#181215'
cursor = '#f6b2e0'

[colors.normal]
black   = '#181215'
red     = '#ff727e'
green   = '#9ef67b'
yellow  = '#ffe072'
blue    = '#e99cd0'
magenta = '#71385f'
cyan    = '#f6b2e0'
white   = '#ffeffa'

[colors.bright]
black   = '#494046'
red     = '#ff9fa7'
green   = '#bfffa5'
yellow  = '#ffeba5'
blue    = '#ffc3eb'
magenta = '#ffcdef'
cyan    = '#ffdff4'
white   = '#fff8fc'
